{...}: {
  imports = [
    ./syncthing.nix
    ./teamspeak.nix
    ./jellyfin.nix
    ./immich.nix
    ./samba.nix
    ./homepage.nix
    ./arr.nix
    ./nginx.nix
    ./gitea.nix
    ./tandoor-recipes.nix
    ./stirling-pdf.nix
    ./paperless.nix
    ./actual.nix
    ./headscale.nix
    ./tailscale.nix
    ./radicale.nix
    ./unifi-controller.nix
    ./searx.nix
    ./metube.nix
    ./it-tools.nix
    ./seafile.nix
    ./convertx.nix
    ./omni-tools.nix
    ./olivetin.nix
    ./authentik.nix
    ./ntfy.nix
    ./arr/jellyfin.nix
    ./home-assistant/home-assistant.nix
    ./home-assistant/mosquitto.nix
    ./home-assistant/zigbee2mqtt.nix
    ./home-assistant/wyoming-whisper.nix
    ./home-assistant/wyoming-piper.nix
    ./home-assistant/matter.nix
    ./home-assistant/otbr.nix
    ./llm/ollama.nix
    ./llm/open-webui.nix
  ];
}
