{...}: {
  imports = [
    ./syncthing.nix
    ./teamspeak.nix
    ./jellyfin.nix
    ./immich.nix
    ./samba.nix
    ./minecraft-servers.nix
    ./home-assistant.nix
    ./homepage.nix
    ./adguardhome.nix
    ./arr.nix
    ./nginx.nix
    ./gitea.nix
    ./tandoor-recipes.nix
    ./llm.nix
    ./stirling-pdf.nix
    ./paperless.nix
    ./grocy.nix
    ./wallos.nix
    ./actual.nix
    ./headscale.nix
    ./tailscale.nix
    ./radicale.nix
    ./unifi-controller.nix
    ./karakeep.nix
    ./searx.nix
    ./metube.nix
    ./it-tools.nix
    ./seafile.nix
    ./convertx.nix
    ./omni-tools.nix
    ./olivetin.nix
    ./monitoring.nix
  ];
}
