{...}: {
  imports = [
    ./syncthing.nix
    ./teamspeak.nix
    ./jellyfin.nix
    ./immich.nix
    ./samba.nix
    ./homepage.nix
    ./arr.nix
    ./nginx.nix
    ./gitea.nix
    ./tandoor-recipes.nix
    ./paperless/paperless.nix
    ./actual/actual.nix
    ./headscale.nix
    ./tailscale.nix
    ./radicale.nix
    ./unifi-controller.nix
    ./searx.nix
    ./metube/metube.nix
    ./seafile.nix
    ./olivetin.nix
    ./authentik.nix
    ./ntfy.nix
    ./restic-backup.nix
    ./arr/jellyfin.nix
    ./home-assistant/home-assistant.nix
    ./home-assistant/mosquitto.nix
    ./home-assistant/zigbee2mqtt.nix
    ./home-assistant/wyoming-whisper.nix
    ./home-assistant/wyoming-piper.nix
    ./home-assistant/matter.nix
    ./home-assistant/otbr.nix
    ./home-assistant/esphome.nix
    ./llm/ollama.nix
    ./llm/open-webui.nix
    ./monitoring/ntfy.nix
    ./stirling-pdf/stirling-pdf.nix
    ./omni-tools/omni-tools.nix
    ./convertx/convertx.nix
  ];
}
